### create numpy arrays and multiply the elements

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,2])
b = np.array([2,3,4])
c = a * b
print("The output is: {}".format(c))

The output is: [2 6 8]


### create a 2d array of floats

In [4]:
a = np.array([[1.0, 2.2, 3.1],
             [3.9, 2.3, 6.5]])
print(a)

[[1.  2.2 3.1]
 [3.9 2.3 6.5]]


### get demensions from array

In [5]:
print('The dimension of a is: {} and the dimension of b is: {}'.format(a.ndim, b.ndim))

The dimension of a is: 2 and the dimension of b is: 1


### get shape of array

In [6]:
print('The dimension of a is: {} and the dimension of b is: {}'.format(a.shape, b.shape))

The dimension of a is: (2, 3) and the dimension of b is: (3,)


### get the data type

In [7]:
print('The dimension of a is: {} and the dimension of b is: {}'.format(a.dtype, b.dtype))

The dimension of a is: float64 and the dimension of b is: int64


### get specific value x[r, w]

In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a.shape

(2, 7)

In [10]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
# say we need to access the 12 from it
print(a[1,4])

12


In [12]:
# another way
print(a[1,-3])

12


### grab a single row and then column

In [13]:
# first row
print(a[0,:])

[1 2 3 4 5 6 7]


In [14]:
# first column
print(a[:,0])

[1 8]


### print specific values through slicing

In [16]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
# print 2 to 6 skipping one value
print(a[0, 1:6:2]) # 1 to 6 step 2

[2 4 6]


### create a numpy array and make the odd values -1

In [19]:
x = np.array([1,2,3,4,5,6,7,8])
output = np.where(x%2==1,-1,x)
print(output)

[-1  2 -1  4 -1  6 -1  8]


### initialize different types of arrays

In [6]:
import numpy as np

# zeros array

x = np.zeros(5)
print(x)


x = np.zeros((5,5))
x

[0. 0. 0. 0. 0.]


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
# all ones matrix

x = np.ones(4)
x

array([1., 1., 1., 1.])

In [10]:
# other number

x = np.full((2,2), 5, dtype='float32')
x

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [12]:
# random decimal number

x = np.random.rand(2,2)
x

array([[0.22284657, 0.32406751],
       [0.6342596 , 0.58508774]])

In [17]:
# random integer values
x = np.random.randint(10, size=(2,2))
x

array([[6, 8],
       [9, 6]])

### indentity matrix

In [20]:
x = np.identity(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### repeat feature

In [28]:
x = np.array([[1,2,3],
              [1,2,3]])
r = np.repeat(x, 3)
print(r) # horizontal
r = np.repeat(x,3, axis=0)
print(r) #vertical

[1 1 1 2 2 2 3 3 3 1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


### exercise 

In [ ]:
'''a = 1,1,1,1,1
       1,0,0,0,1
       1,0,9,0,1
       1,0,0,0,1
       1,1,1,1,1'''

In [32]:
one = np.ones((5,5))
print (one)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [33]:
zero = np.zeros((3,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
# replace the middle element with 9
zero[1,1] = 9
zero

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [36]:
# now replace this with one


one[1:4,1:4] = zero
one

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### note while copying arrays

In [37]:
a = np.array([1,2,3])
b = a 
b

array([1, 2, 3])

In [38]:
# but when b is changed a will be changed

b[0] = 2
print(b)
print(a)

[2 2 3]
[2 2 3]


In [44]:
# since we don't want that because they are pointing to same referece 

a = np.array([1,2,3])
b = a.copy()
print(a)
print(b)
b[0] = 2
print('*******')
print(a)
print(b)

[1 2 3]
[1 2 3]
*******
[1 2 3]
[2 2 3]


### mathematics

In [46]:
a = np.array([1,2,3])
a + 2 # element wise operation 

array([3, 4, 5])

In [48]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [49]:
# note in linear algebra the col of a must match with row of b to multiply

x = np.matmul(a,b) # result will be of size row_a x col_b
x

array([[6., 6.],
       [6., 6.]])

In [52]:
# find the determinant
a = np.identity(3)
print(a)
print(np.linalg.det(a))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
1.0


##### stats

In [61]:
# min max

a = np.array([[1,2,3,4], [6,7,8,9]])
print(a)
mini_h = np.min(a, axis=0)
mini_v = np.min(a, axis=1)
print("The vertical min is: {} & the horizontal min is: {}".format(mini_v,mini_h))

[[1 2 3 4]
 [6 7 8 9]]
The vertical min is: [1 6] & the horizontal min is: [1 2 3 4]


In [64]:
# find sum of row and columns
# note axis = 0 means downwards
sum_c = np.sum(a, axis=0)
sum_r = np.sum(a, axis=1)
print("The row sum is: {} & the col sum is: {}".format(sum_r, sum_c))

The row sum is: [10 30] & the col sum is: [ 7  9 11 13]


### re-organizaing array

In [65]:
a = np.array([[1,2,3,4], [5,6,7,8]])
print(a.shape)

(2, 4)


In [66]:
# reshaping the array to dimesions equal to the product of shape r & c

a.reshape(1,8)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

##### vertically stacking arrays

In [67]:
ar1 = np.array([1,2,3,4,5])
ar2 = np.array([3,4,5,6,7])

stack = np.vstack([ar1,ar2])
stack

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7]])

In [68]:
# stack unlimited amount of times

stack = np.vstack([ar1, ar1, ar2, ar1, ar2, ar2])
stack

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [3, 4, 5, 6, 7]])

##### horizontal stack

In [70]:
stack = np.hstack([ar1, ar2, ar2, ar1])
stack

array([1, 2, 3, 4, 5, 3, 4, 5, 6, 7, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5])